app/admin_shop/models.py
from app import db
from datetime import datetime


# ADMIN STORE models

class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    display = db.Column(db.String(40), nullable=False)
    create_date = db.Column(db.DateTime,default=datetime.utcnow, nullable=False)
    catgen = db.relationship("CategoryGeneral", backref="category", lazy="dynamic")

    def __repr__(self):
        return '<Category {}>'.format(self.name)


class CatGenSizeColor(db.Model):
    __tablename__ = 'catgen_size_color'
    catgen_id = db.Column(db.Integer, db.ForeignKey('category_general.id'), primary_key=True)
    size_id = db.Column(db.Integer, db.ForeignKey('size.id'), primary_key=True)
    color_id = db.Column(db.Integer, db.ForeignKey('color.id'), primary_key=True)
    quantity = db.Column(db.Integer, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    update_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    create_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    def __repr__(self):
        return '<CatGenSizeColor cat_id: {catgen_id}, size_id: {size_id}, \
            color_id: {color_id}>'.format(catgen_id=self.catgen_id, \
            size_id=self.size_id, color_id=self.color_id) 


class Size(db.Model):
    __tablename__ = 'size'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    update_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    create_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    #joined means all rows returned
    #dynamic means return query objects instead of items so you can use filter
    #cascade delete-orphan means if student object is deleted then association table row is also deleted
    catgen_color = db.relationship('CatGenSizeColor',
                            foreign_keys=[CatGenSizeColor.size_id],
                            backref=db.backref('size',lazy='joined'),
                            lazy='joined',
                            cascade='all, delete-orphan')

    def __repr__(self):
        return '<Size {}>'.format(self.name)


class Color(db.Model):
    __tablename__ = 'color'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    update_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    create_date = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    catgen_size = db.relationship('CatGenSizeColor',
                            foreign_keys=[CatGenSizeColor.color_id],
                            backref=db.backref('color',lazy='joined'),
                            lazy='joined',
                            cascade='all, delete-orphan')

    def __repr__(self):
        return '<Color {}>'.format(self.name)


class CategoryGeneral(db.Model):
    __tablename__ = 'category_general'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(1000), nullable=False)
    image_id1 = db.Column(db.Integer, db.ForeignKey('images.id'), nullable=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    update_date = db.Column(
        db.DateTime, default=datetime.utcnow, nullable=False)
    create_date = db.Column(db.DateTime,default=datetime.utcnow, nullable=False)
    size_color = db.relationship('CatGenSizeColor',
                        foreign_keys=[CatGenSizeColor.catgen_id],
                        backref=db.backref('catgen',lazy='joined'),
                        lazy='joined',
                        cascade='all, delete-orphan')

    def __repr__(self):
        return '<CategoryGeneral {}>'.format(self.title)

app/admin_shop/__init__.py
from flask import Blueprint

bp = Blueprint('admin_shop', __name__)

from app.admin_shop import routes

app/admin_shop/routes.py
from flask import render_template, request, current_app, flash, session
from app import db
from app.admin_shop import bp
from flask_login import login_required
from app.breadcrumb import set_breadcrumb
from app.admin_shop.models import Category, CategoryGeneral, Size, Color
from sqlalchemy import asc


# ADMIN SHOP routes

@bp.route('/shop',methods=['GET','POST'])
@login_required
@set_breadcrumb('home shop')
def shop():
    if 'shop_show_type' in session:
        show_type = session['shop_show_type']
    else:
        show_type = 'all'
    if request.method == 'POST':
        s = request.form.get('show_type')
        if s=='all':
            show_type='all'
        else:
            if s:
                cat = Category.query.filter_by(id=int(s)).first()
                if not cat:
                    flash('Show type error', 'danger')
                else:
                    show_type = s
    page = request.args.get('page',1,type=int)
    category = Category.query.order_by(asc(Category.display)).all()
    if show_type == 'all':
        session['shop_show_type']='all'
        catgen = CategoryGeneral.query.order_by(asc(CategoryGeneral.title)) \
            .paginate(page,current_app.config['SHOP_PER_PAGE'],False)
    else:
        session['shop_show_type'] = show_type
        catgen = CategoryGeneral.query.join(Category) \
            .filter(Category.id==int(show_type)) \
            .order_by(asc(CategoryGeneral.title)) \
            .paginate(page,current_app.config['SHOP_PER_PAGE'],False)
    return render_template('admin_shop/shop.html',catgen=catgen
        ,category=category,show_type=show_type)


@bp.route('/product',methods=['GET','POST'])
@login_required
@set_breadcrumb('home shop product')
def product():
    if request.method == 'POST':
        category = request.form.get('category')
        title = request.form.get('title')
        description = request.form.get('description')
        variants = request.form.get('form_variants')
    category = Category.query.order_by(asc(Category.display)).all()
    size = Size.query.order_by(asc(Size.name)).all()
    color = Color.query.order_by(asc(Color.name)).all()
    return render_template('admin_shop/product.html',category=category
        ,size=size,color=color)

app/templates/admin_shop/product.html
{% extends "shared/base_main.html" %}
{% from 'shared/macros/_form_image.html' import form_image with context %}
{% block title %}Product{% endblock %}

{% block app_content %}
<div id="this-block">
  <div class="mb-6 content">
    <form ref="form" action="{{ url_for('admin_shop.product') }}" 
      method="post" enctype="multipart/form-data">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input type="hidden" name="form_variants" :value="formVariants"/>

      <div class="level">
        <div class="level-left">
        </div>
        <div class="level-right">
          <input type="submit" @click.prevent="doValidate" 
            name="submit_btn" value="Submit" class="button is-link"/>
        </div>
      </div>

      <div class="field">
        <label class="label">Category*</label>
        <div class="select">
          <select name="category" v-model="category" autofocus>
            <option value="select">-- Select Category --</option>
            {% for c in category %}
            <option value="{{ c.id }}">{{ c.name }}</option>
            {% endfor %}
          </select>
        </div>
        <p v-if="errorMsg[0]" class="help is-danger">[[ errorMsg[0] ]]</p>
      </div>
      
      <div class="field">
        <label class="label">Title*</label>
        <div class="control">
          <input
            name="title"
            class="input"
            type="text"
            v-model="title">
        </div>
        <p v-if="errorMsg[1]" class="help is-danger">[[ errorMsg[1] ]]</p>
      </div>

      <div class="field">
        <label class="label">Description*</label>
        <div class="control">
          <textarea id="description" name="description" class="shoptiny textarea">
          </textarea>
        </div>
        <p v-if="errorMsg[2]" class="help is-danger">[[ errorMsg[2] ]]</p>
      </div>
      <hr/>

      <p><label class="label">Variants</label></p>
      <div class="field is-grouped">
        <div class="field-body">
          <div class="field is-narrow">
            <label class="label">Size</label>
            <div class="select">
              <select v-model="size_index">
                <option value="select">-- Select Size --</option>
                {% for s in size %}
                <option value="{{ loop.index0 }}">{{ s.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="field is-narrow">
            <label class="label">Color</label>
            <div class="select">
              <select v-model="color_index">
                <option value="select">-- Select Color --</option>
                {% for c in color %}
                <option value="{{ loop.index0 }}">{{ c.name }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <div class="field">
            <label class="label">&nbsp;</label>
            <input type="submit" @click.prevent="addVariant" 
            name="submit_btn" value="Add Variant" class="button is-link"/>
          </div>
        </div>
      </div>
      <p v-if="errorMsg[3]" class="help is-danger">[[ errorMsg[3] ]]</p>

      <div v-if="variants.length>0" class="table-container">
        <table class="table is-narrow is-hoverable">
          <thead>
            <tr>
              <th></th>
              <th></th>
              <th>Quantity</th>
              <th>SKU</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(v, index) in variants">
              <td>[[ sizeTable[v.size_index].name ]]</td>
              <td>[[ colorTable[v.color_index].name ]]</td>
              <td class="is-narrow">
                <input :name="'quantity'+index" v-model="formVariants[[index]].quantity"
                  class="input" type="text">
              </td>
              <td>
                <input :name="'sku'+index" class="input" v-model="formVariants[[index]].sku"
                  type="text">
              </td>
              <td>
                <a @click.prevent="removeVariant([[index]])">
                  <i class="fas fa-times-circle"></i>
                </a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <hr/>

      <div class="pt-4 field">
        <label class="label">Current image*</label>
        <div class="control">
          <p>Empty</p>
        </div>
      </div>
      {{ form_image(1,4) }}

      <div class="pt-4 field">
        <div class="select">
          <select v-model="numImg">
            <option value="1">More images?</option>
            <option value="2">Upload one more</option>
            <option value="3">Upload two more</option>
          </select>
        </div>
      </div>

      <div v-show="numImg==2||numImg==3">
        <div class="pt-4 field">
          <label class="label">Image 2</label>
          <div class="control">
            <p>Empty</p>
          </div>
        </div>
        {{ form_image(2,5) }}
      </div>

      <div v-show="numImg==3">
        <div class="pt-4 field">
          <label class="label">Image 3</label>
          <div class="control">
            <p>Empty</p>
          </div>
        </div>
        {{ form_image(3,6) }}
      </div>

    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  new Vue({
    el: '#this-block',
    delimiters: ['[[', ']]'],
    data() {
      return {
        category: 'select',
        title: '',
        description: '',
        size_index: 'select',
        color_index: 'select',
        quantity: 0,
        errorMsg: ['','','','','','',''],
        filename1: 'No file selected',
        newimage1: 'upload',
        numImg: '1',
        filename2: 'No file selected',
        newimage2: 'upload',
        filename3: 'No file selected',
        newimage3: 'upload',
        variants: [],
        sizeTable: [],
        colorTable: [],
        formVariants: []
      }
    },
    methods: {
      chkFileSize(imgNum,errNum) {
        let fs = this.$refs['imgupload'+imgNum].files[0]
        if (fs) {
          if((fs.size/1024) > 1024) {
            Vue.set(this.errorMsg, errNum, 'Image cannot be larger than 1MB')
          }
        }
      },
      clearErrors() {
        for (let i=0; i<this.errorMsg.length;i++) {
          this.errorMsg[i] = ''
        }
      },
      hasError() {
        err = false
        for(let i=0; i<this.errorMsg.length; i++) {
          if(this.errorMsg[i] != '') err = true
        }
        return err
      },
      doValidate() {
        this.clearErrors()
        let description = tinyMCE.get('description').getContent()
        if (this.category == 'select') {
          Vue.set(this.errorMsg, 0, 'This field is mandatory')
        }
        if (this.title.length == 0) {
          Vue.set(this.errorMsg, 1, 'This field is mandatory')
        } else if (this.title.length > 100) {
          Vue.set(this.errorMsg, 1, 'Maximum 100 characters')
        }
        if (description.length == 0) {
          Vue.set(this.errorMsg, 2, 'This field is mandatory')
        } else if (description.length > 1000) {
          Vue.set(this.errorMsg, 2, 'Maximum 1000 characters')
        }
        if (this['newimage1']=='upload') {
          this.chkFileSize(1,4)
        }
        let upl = this.$refs['imgupload1'] ? this.$refs['imgupload1'].value: ''
        let sel = this.$refs['imgselect1'] ? this.$refs['imgselect1'].value: ''
        if (!upl && !sel) {
          Vue.set(this.errorMsg, 4, 'Image is mandatory')
        }
        if (this.numImg=='2'||this.numImg=='3') {
          for(i=2;i<Number(this.numImg)+1;i++) {
            if (this['newimage'+i]=='upload') {
              this.chkFileSize(i,i+3)
            }
          }
        }
        if (!this.hasError()) {
          this.formVariants.forEach((fv, index) => {
            Vue.set(this.formVariants, index, JSON.stringify(fv))
          })
          this.$nextTick(() => {
            this.$refs.form.submit()
          })
        }
      },
      fileSelected(evt,img_num) {
        if (evt.target.files.length > 0) {
          this['filename'+img_num] = evt.target.files[0].name
        }
      },
      clearSelection(ref,img_num,err_num) {
        this.$refs[ref].value = ''
        Vue.set(this.errorMsg, err_num, '')
        this['filename'+img_num] = 'No file selected'
      },
      checkVariantSelected(size_id,color_id) {
        let found = false
        this.formVariants.forEach(function (fv) {
          if (fv.size_id == size_id && fv.color_id == color_id) found = true
        })
        return found
      },
      removeVariant(index) {
        this.variants.splice(index,1)
        this.formVariants.splice(index,1)
      },
      addVariant() {
        Vue.set(this.errorMsg, 3, '')
        if (this.size_index=='select' || this.color_index=='select') {
          Vue.set(this.errorMsg, 3, 'Both size and color must be selected')
        } else if (this.checkVariantSelected(
            this.sizeTable[this.size_index].id, this.colorTable[this.color_index].id)) {
          Vue.set(this.errorMsg, 3, 'Variant already selected')
        } else {
          let v = {
            'size_index' : this.size_index,
            'color_index' : this.color_index
          }
          this.variants.push(v)
          let fv = {
            'size_id' : this.sizeTable[this.size_index].id,
            'color_id' : this.colorTable[this.color_index].id,
            'quantity' : '0',
            'sku' : ''
          }
          this.formVariants.push(fv)
        }
      }
    },
    filters: {
      truncate: function (text, length, suffix) {
        if (text.length > length) {
            return text.substring(0, length) + suffix;
        } else {
            return text;
        }
      }
    },
    mounted() {
      let itemSize = {}
      let itemColor = {}
      {% for s in size %}
      itemSize = {
        'id' : {{ s.id }},
        'name' : '{{ s.name }}'
      }
      this.sizeTable.push(itemSize)
      {% endfor %}
      {% for c in color %}
      itemColor = {
        'id' : {{ c.id }},
        'name' : '{{ c.name }}'
      }
      this.colorTable.push(itemColor)
      {% endfor %}
    }
  })
</script>
{% include 'shared/tinymce/_tinymce_shop.html' %}
{% endblock %}

app/templates/admin_shop/shop.html
{% extends "shared/base_main.html" %}
{% from 'shared/macros/_pagination.html' import pagination %}
{% block title %}Shop{% endblock %}

{% block app_content %}
<div id="this-block">

  <form ref="showForm" method="post" action="{{ url_for('admin_shop.shop') }}">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="hidden" name="show_type" :value="showType"/>
  </form>

  <div class="level">
    <div class="level-left">
      <span class="mr-2">Category</span>
      <div class="mr-4 select">
        <select v-model="showType" @change="getShow">
          {% if category %}
          <option value="all">All</option>
          {% endif %}
          {% for c in category %}
          <option value="{{ c.id }}">{{ c.display }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
    <div class="level-right">
      <button class="button is-link" @click="gotoURL('{{ url_for('admin_shop.product') }}')">
        Add Product
      </button>
    </div>
  </div>
  <table class="table is-narrow is-striped is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th></th>
        <th>Product</th>
        <th>Inventory</th>
        <th>Category</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for c in catgen.items %}
      <tr>
        <td>Image</td>
        <td>{{ c.title }}</td>
        <td>?</td>
        <td>{{ c.category.display }}</td>
        <td class="has-text-right"><a href="{{ url_for('admin_shop') }}"><i class="far fa-edit" title="edit"></i></a></td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  {% if catgen.pages > 1 %}
  {{ pagination(catgen,'admin_sshop') }}
  {% endif %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  new Vue({
    el: '#this-block',
    delimiters: ['[[', ']]'],
    data() {
      return {
        showType: '{{ show_type or "all" }}'
      }
    },
    methods: {
      getShow() {
        this.$nextTick(() => {
          this.$refs.showForm.submit()
        })
      },
      gotoURL(url) {
        window.location.href=(url)
      }
    }
  })
</script>
{% endblock %}