app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, template_folder='templates', static_folder='dist', static_url_path='/')

from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp
from app.admin_page.models import PageHomeMain, PageStatus


@bp.route('/')
def index():
    main = PageHomeMain.query.filter_by(page_status=PageStatus.getStatus('published')).first()
    return render_template('index.html', main=main)



@bp.route('/try2')
def try2():
    return render_template('try2.html')

app/main/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Flask & Tailwind</title>
  <link rel="stylesheet" href="{{ url_for('main.static', filename='css/styles.css') }}">
</head>
<body class="debug-screens">
  <header class="relative h-60 sm:h-72 lg:h-96 bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500">
    <div class="relative flex justify-end px-4 py-4">
      <ul class="flex">
        <li class="mr-5"><a href="{{ url_for('main.try2') }}">Try 2</a></li>
      </ul>
    </div>
    <svg class="absolute bottom-0 w-full h-1/3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="none">
      <polygon fill="white" points="0,100 100,100 100,0 0,100"/>
    </svg>
  </header>
  
  <section class="relative flex justify-center w-1/2 mx-auto mb-6 -mt-44 sm:-mt-56 lg:-mt-80">
    {% if main.image1 %}
    <img class="w-full animate-fadeIn" src="{{ url_for('static', filename='uploads/page/' ~ main.image1.filename) }}" />
    {% endif %}
  </section>

  <div class="container flex justify-center max-w-full p-10">
    <article class="relative max-w-full prose">
      <article class="relative max-w-full prose">
      <h1>{{ main.heading }}</h1>
      {{ main.text|safe }}
    </article>
  </div>

</body>
</html>

app/main/templates/try2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Flask & Tailwind</title>
  <link rel="stylesheet" href="{{ url_for('main.static', filename='css/styles.css') }}">
</head>
<body class="debug-screens">
  <h1 class="prose">Another design</h1>

</body>
</html>