app/admin_page/models.py
from app import db
from datetime import datetime


# ADMIN PAGE models

class Page(db.Model):
    __tablename__ = 'page'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    display = db.Column(db.String(20), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    last_publish_date = db.Column(
        db.DateTime, default=datetime.utcnow, nullable=False)
    page_home_main = db.relationship(
        "PageHomeMain", backref="page", lazy="dynamic")

    @staticmethod
    def getPage(name):
        return Page.query.filter_by(name=name).first()

    def __repr__(self):
        return '<Page {}>'.format(self.name)


class PageStatus(db.Model):
    __tablename__ = 'page_status'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    create_date = db.Column(db.DateTime,default=datetime.utcnow, nullable=False)
    page_home_main = db.relationship(
        "PageHomeMain", backref="page_status", lazy="dynamic")

    @staticmethod
    def getStatus(name):
        return PageStatus.query.filter_by(name=name).first()

    def __repr__(self):
        return '<PageStatus {}>'.format(self.name)


class PageHomeMain(db.Model):
    __tablename__ = 'page_home_main'
    id = db.Column(db.Integer, primary_key=True)
    heading = db.Column(db.String(50), nullable=False)
    text = db.Column(db.String(5000), nullable=False)
    image_id1 = db.Column(db.Integer, db.ForeignKey('images.id'), nullable=True)
    status_id = db.Column(db.Integer, db.ForeignKey('page_status.id'), nullable=False)
    page_id = db.Column(db.Integer, db.ForeignKey('page.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    update_date = db.Column(
        db.DateTime, default=datetime.utcnow, nullable=False)
    create_date = db.Column(db.DateTime,default=datetime.utcnow, nullable=False)

    def __repr__(self):
        return '<PageHomeMain {}>'.format(self.heading)

app/admin_page/__init__.py
from flask import Blueprint

bp = Blueprint('admin_page', __name__)

from app.admin_page import routes

app/admin_page/routes.py
from flask import render_template, request, current_app
from flask_login import login_required
from app.admin_page import bp
from app.admin_page.models import Page, PageHomeMain
from app.breadcrumb import set_breadcrumb
from .common import page_post


# ADMIN PAGE routes 

@bp.route('/page', methods=['GET'])
@login_required
@set_breadcrumb('home page')
def page():
    page = request.args.get('page',1,type=int)
    pages = Page.query.order_by(Page.name.asc()) \
    .paginate(page,current_app.config['PAGES_PER_PAGE'],False)

    return render_template('admin_page/page.html',pages=pages)


@bp.route('/page/page_home_main', methods=['GET', 'POST'])
@login_required
@set_breadcrumb('home page page-home-main')
def page_home_main():
    fields = [
        {'name': 'heading', 'type': 'str'},
        {'name': 'text', 'type': 'str'}
    ]
    edit_ver, all_ver = page_post(PageHomeMain,'home_main', fields, num_images=1)
    return render_template('admin_page/page_home_main.html', edit_ver=edit_ver, all_ver=all_ver, num_images=1)

app/templates/admin_page/page.html
{% extends "shared/base_main.html" %}
{% from 'shared/macros/_pagination.html' import pagination %}
{% block title %}Page{% endblock %}

{% block app_content %}
<div class="table-container">
  <table class="table is-narrow is-striped is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Page</th>
        <th>Published</th>
        <th>by</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% if pages.items|length == 0 %}
    <tr><td class="content">No pages in database</td></tr>
    {% endif %}
    {% for page in pages.items %}
      <tr>
        <td>{{ page.display }}</td>
        <td>{{ moment(page.last_publish_date).format('D MMM YYYY hh:mm') }}</td>
        <td>{{ page.last_publish_by.email }}</td>
        {% if page.name == 'home_main' %}
        <td class="has-text-right"><a href="{{ url_for('admin_page.page_home_main') }}"><i class="far fa-edit" title="edit"></i></a></td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>

{% if pages.pages > 1 %}
{{ pagination(comment,'admin_page.page') }}
{% endif %}
{% endblock %}

app/templates/admin_page/page_home_main.html
{% extends "shared/base_main.html" %}
{% from 'shared/macros/_page_version.html' import version with context %}
{% from 'shared/macros/_form_image.html' import form_image with context %}
{% block title %}Page Home Main{% endblock %}

{% block app_content %}
<div id="this-block">
  <div class="mb-6 content">
    <form ref="form" action="{{ url_for('admin_page.page_home_main') }}" 
      method="post" enctype="multipart/form-data">
      <!-- required -->
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <input type="hidden" name="id" value="{{ edit_ver.id }}">
      <input type="hidden" name="action" :value="action">
      {% include 'shared/macros/_page_edit_buttons.html' %}
      <!-- if images -->
      <input type="hidden" name="image_id1" :value="data_img.image_id1"/>
     
      <div class="field">
        <label class="label">Heading*</label>
        <div class="control">
          <input 
            autofocus
            name="heading"
            class="input"
            type="text"
            v-model="data.heading">
        </div>
        <p v-if="errorMsg[0]" class="help is-danger">[[ errorMsg[0] ]]</p>
      </div>

      <div class="field">
        <label class="label">Main Text*</label>
        <div class="control">
          <textarea id="text" class="simpletiny" name="text" v-model="data.text">
          </textarea>
        </div>
        <p v-if="errorMsg[1]" class="help is-danger">[[ errorMsg[2] ]]</p>
      </div>

      <div class="pt-4 field">
        <label class="label">Current image*</label>
        <div class="control">
          {% if edit_ver.image1.filename %}
          <p class="is-size-7">{{ edit_ver.image1.filename }}</p>
          <img src="{{ url_for('static', filename='uploads/page/thumbnails/' ~ edit_ver.image1.thumbnail) }}">
          {% else %}
          <p>Empty</p>
          {% endif %}
        </div>
      </div>
      <!-- if images -->
      {% if edit_ver.page_status.name == 'draft' %}
      {{ form_image(1,2) }}
      {% endif %}
    </form>
    <!-- required -->
    {{ version(edit_ver.page.name) }}
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
new Vue({
  el: '#this-block',
  delimiters: ['[[', ']]'],
  data() {
    return {
      data: {
        heading: '{{ edit_ver.heading or "" }}',
        text: `{{ edit_ver.text|safe or "" }}`,
      },
      data_img: {
        filename1: 'No file selected',
        newimage1: 'upload',
        image_id1: '{{ edit_ver.image_id1 or "none" }}',
      },
      num_images: {{ num_images }},
      errorMsg: ['','',''],
      action: '',
    }
  },
  methods: {
    /* required */
    clearErrors() {
      for (let i=0; i<this.errorMsg.length;i++) {
        this.errorMsg[i] = ''
      }
    },
    hasError() {
      err = false
      for(let i=0; i<this.errorMsg.length; i++) {
        if(this.errorMsg[i] != '') err = true
      }
      return err
    },
    doValidate(evt) {
      if (evt.target.value != "Delete") {
        this.clearErrors()
        let text= tinyMCE.get('text').getContent()
        if (this.data.heading.length == 0) {
          Vue.set(this.errorMsg, 0, 'This is a mandatory field')
        } else if (this.data.heading.length > 50) {
          Vue.set(this.errorMsg, 0, 'Maximum 50 characters')
        }
        if (text.length == 0) {
          Vue.set(this.errorMsg, 2, 'This is a mandatory field')
        } else if (text.length > 5000) {
          Vue.set(this.errorMsg, 2, 'Maximum 1000 characters')
        }
        if (evt.target.value != 'Save as draft') {
          if (this.data_img.newimage1=='upload') {
            let prev_err = -1
            let fs = this.$refs['imgupload1'].files[0]
            if (fs) {
              if((fs.size/1024) > 1024) {
                Vue.set(this.errorMsg, 3, 'Image cannot be larger than 1MB')
              }
            }
          }
        }
      }
      if (!this.hasError()) {
        this.action = evt.target.value
        for (let n=1; n<this.num_images+1; n++) {
          let upl = this.$refs['imgupload'+n] ? this.$refs['imgupload'+n].value: ''
          let sel = this.$refs['imgselect'+n] ? this.$refs['imgselect'+n].value: ''
          if (upl || sel) {
            this.data_img['image_id'+n]=''
          }
        }
        this.$nextTick(() => {
          this.$refs.form.submit()
        })
      }
    },
    /* if images */
    fileSelected(evt,img_num) {
      if (evt.target.files.length > 0) {
        this.data_img['filename'+img_num] = evt.target.files[0].name
      }
    },
    clearSelection(ref,img_num,err_num) {
      this.$refs[ref].value = ''
      Vue.set(this.errorMsg, err_num, '')
      this.data_img['filename'+img_num] = 'No file selected'
    }
  },
  /* if images */
  filters: {
    truncate: function (text, length, suffix) {
      if (text.length > length) {
          return text.substring(0, length) + suffix
      } else {
          return text
      }
    }
  }
})
</script>
{% include 'shared/tinymce/_tinymce_simple.html' %}
{% endblock %}