app/admin_auth/models.py
from flask import current_app
from flask_login import UserMixin, AnonymousUserMixin
from datetime import datetime, timedelta
from hashlib import md5
from werkzeug.security import generate_password_hash, check_password_hash
import jwt
from app import db, login_manager


# ADMIN AUTH models

class User(db.Model, UserMixin):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), index=True, unique=True, nullable=False)
    firstname = db.Column(db.String(20), nullable=False)
    lastname = db.Column(db.String(50), nullable=False)
    password_hash = db.Column(db.String(200))
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'), nullable=False)
    prev_login = db.Column(db.DateTime,default=datetime.utcnow, nullable=True)
    last_login = db.Column(db.DateTime,default=datetime.utcnow, nullable=True)
    create_date = db.Column(db.DateTime,default=datetime.utcnow, nullable=False)
    pages = db.relationship('Page', backref='last_publish_by', lazy='dynamic')
    page_home_main = db.relationship('PageHomeMain', backref='author', lazy='dynamic')
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    comments = db.relationship('Comment', backref='user', lazy='dynamic')
    site_setting = db.relationship('SiteSetting', backref='user', lazy='dynamic')

    # generate hash of given password
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    # return hash of given password
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=monsterid&s={}'.format(digest, size)

    # return true if user is admin, false otherwise
    def is_admin(self):
        return self.role.name == 'admin'

    # creates token of user object
    # decode('utf-8') converts token to string
    def get_reset_password_token(self, expires_in=current_app.config['FORGOT_PASSWORD_TOKEN_EXPIRE']):
        return jwt.encode(
            {'reset_password': self.id, 'exp': datetime.utcnow() + timedelta(seconds=expires_in)},
            current_app.config['SECRET_KEY'], algorithm='HS256')

    # decodes token and returns user object
    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)

    def to_dict(self):
        data = {
            'email' : self.email,
            'first_name' : self.firstname,
            'last_name' : self.lastname
        }
        return data

    def __repr__(self):
        return '<User {}>'.format(self.email)


# This allows application to freely call these methods even if you're not logged in
class AnonymousUser(AnonymousUserMixin):
    def set_password(self, password):
        return False
    def check_password(self, password):
        return False
    def avatar(self, size):
        return False
    def is_admin(self):
        return False
    def get_reset_password_token(self, expires_in=current_app.config['FORGOT_PASSWORD_TOKEN_EXPIRE']):
        return False
# This tells flask login which class to use if user is not logged in
login_manager.anonymous_user = AnonymousUser


class Role(db.Model):
    __tablename__='role'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, nullable=False)
    users = db.relationship('User',backref='role',lazy='dynamic')


# Used by flask-login
# This callback is used to reload the user object from the user ID stored in the session
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/admin_auth/__init__.py
from flask import Blueprint

bp = Blueprint('admin_auth', __name__)

from app.admin_auth import routes

app/admin_auth/routes.py
from flask import render_template, redirect, url_for, flash, request, session, current_app
from flask_login import current_user, login_user, logout_user, login_required
from app import db, login_manager
from app.admin_auth import bp
from app.admin_auth.email import send_password_reset_email
from app.admin_auth.models import User
from werkzeug.urls import url_parse
from datetime import datetime
from app.admin_main.shared import log


# ADMIN AUTH routes

@bp.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin_main.index'))
    next_page = request.args.get('next')
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        remember_me = request.form.get('remember_me')

        user = User.query.filter_by(email=email).first()
        if user is None or not user.check_password(password):
            flash('Invalid username or password','danger')
            return redirect(url_for('admin_auth.login',next=next_page))

        if remember_me == 'y':
            rem = True
        else:
            rem = False
        login_user(user, remember=rem)
        user.prev_login = user.last_login
        user.last_login = datetime.utcnow()
        db.session.add(user)
        db.session.commit()
        flash('You are now logged in','success')

        # in case url is absolute we will ignore, we only want a relative url
        # netloc returns the www.website.com part
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            return redirect(url_for('admin_main.index'))
        return redirect(url_for(next_page))

    return render_template('admin_auth/login.html', main_url=current_app.config['MAIN_URL'])


@bp.route('/logout')
@login_required
def logout():
    session.pop('edit_post',None)
    logout_user()
    flash('You are now logged out','success')
    return redirect(url_for('admin_auth.login'))


@bp.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('admin_auth.login'))
    if request.method == 'POST':
        email = request.form.get('email')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        password = request.form.get('password')
        user = User(email=email, firstname=firstname, \
                    lastname=lastname, )
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        flash('Registration successful!','success')
        return redirect(url_for('admin_auth.login'))
    return render_template('admin_auth/register.html')


@bp.route('/forgot_password',methods=['GET','POST'])
def forgot_password():
    if current_user.is_authenticated:
        return redirect(url_for('admin_auth.login'))
    if request.method == 'POST':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if user:
            if not send_password_reset_email(user):
                flash('Sorry system error','danger')
        flash('Check your email for instructions to reset your password','success')
    return render_template('admin_auth/forgot_password.html', main_url=current_app.config['MAIN_URL'])


@bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('admin_auth.login'))
    user = User.verify_reset_password_token(token)
    if not user:
        flash('Token has expired or is no longer valid','danger')
        return redirect(url_for('admin_auth.login'))
    if request.method == 'POST':
        password = request.form.get('password')
        user.set_password(password)
        db.session.commit()
        flash('Your password has been reset','success')
        return redirect(url_for('admin_auth.login'))
    return render_template('admin_auth/reset_password.html')


# handler when you are trying to access a page but you are not logged in
@login_manager.unauthorized_handler
def unauthorized():
    #flash('You must be logged in to view this page.','danger')
    return redirect(url_for('admin_auth.login',next=request.endpoint))

app/templates/admin_auth/base_auth.html
{% extends "shared/base.html" %}

{% block content %}
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <article class="message is-{{ category }}">
        <div class="message-body">{{ message }}</div>
      </article>
    {% endfor %}
  {% endif %}
{% endwith %}

<div class="container">
  <div class="pt-6 pl-2 pr-2 columns is-justify-content-center">
    <div class="column is-narrow">
      <div class="hero is-small is-primary">
        <div class="hero-body">

          <div class="p-2 title is-3 has-text-centered has-text-white is-family-secondary">
              Flask CMS
          </div>

        </div>
      </div>
      {% block app_content %}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

app/templates/admin_auth/email_reset_password.html
<p>Dear {{ user.firstname }}</p>
<p>
    To reset your password
    <a href="{{ url_for('admin_auth.reset_password', token=token, _external=True) }}">
        click here
    </a>.
</p>
<p>Alternatively, you can paste the following link in your browser's address bar:</p>
<p>{{ url_for('admin_auth.reset_password', token=token, _external=True) }}</p>
<p>If you have not requested a password reset simply ignore this message.</p>
<p>Regards</p>
<p>Kevin<br/>
(kevin7.net)
</p>

app/templates/admin_auth/forgot_password.html
{% extends "admin_auth/base_auth.html" %}
{% block title %}Forgot Password{% endblock %}

{% block app_content %}
<div id="this-block">

  <form
    ref="forgotPasswordForm"
    action="{{ url_for('admin_auth.forgot_password') }}"
    method="post"
    class="box">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    <div class="notification is-info is-light is-flex-wrap-wrap is-size-7">
      Please enter your email. You will receive<br/>
      an email with instructions on how to<br/>
      reset your password.
    </div>
    <div class="field">
      <div class="label">Email</div>
      <div class="control has-icons-left">
        <input 
          autofocus
          name="email"
          class="input"
          type="text"
          v-model="email">
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </div>
      <p v-if="errorMsg[0]" class="help is-danger">[[ errorMsg[0] ]]</p>
    </div>

    <div class="pt-3 field">
      <div class="control is-expanded has-text-right">
        <input 
          type="submit"
          @click.prevent="doValidate"
          name="submit_btn" 
          class="button is-link">
      </div>
    </div>
  </form>

  <div class="content is-size-7 has-text-centered">
    <p><a href="{{ url_for('admin_auth.login') }}">Ready to sign in?</a></p>
    <p><a href="{{ main_url }}">&larr; Go to main site</a></p>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  new Vue({
    el: '#this-block',
    delimiters: ['[[', ']]'],
    data() {
      return {
        email: '',
        errorMsg: ['']
      }
    },
    methods: {
      clearErrors() {
        for (let i=0; i<this.errorMsg.length;i++) {
          this.errorMsg[i] = ''
        }
      },
      hasError() {
        err = false
        for(let i=0; i<this.errorMsg.length; i++) {
          if(this.errorMsg[i] != '') err = true
        }
        return err
      },
      doValidate() {
        this.clearErrors()
        if (this.email.length == 0) {
          Vue.set(this.errorMsg, 0, 'This is a mandatory field')
        }
        if (!this.hasError()) {
          this.$refs.forgotPasswordForm.submit()
        }
      }
    }
  })
</script>
{% endblock %}

app/templates/admin_auth/login.html
{% extends "admin_auth/base_auth.html" %}
{% block title %}Login{% endblock %}

{% block app_content %}
<div id="this-block">

  <form 
    ref="loginForm" 
    method="post" 
    action="{{ url_for('admin_auth.login') }}" 
    class="box">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    <div class="field">
      <div class="label">Email</div>
      <div class="control has-icons-left">
        <input 
          autofocus
          name="email"
          class="input"
          type="text"
          v-model="email">
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </div>
      <p v-if="errorMsg[0]" class="help is-danger">[[ errorMsg[0] ]]</p>
    </div>

    <div class="field">
      <div class="label">Password</div>
      <div class="control has-icons-left">
        <input 
          name="password"
          class="input"
          type="password"
          v-model="password">
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </div>
      <p v-if="errorMsg[1]" class="help is-danger">[[ errorMsg[1] ]]</p>
    </div>

    <div class="pt-3 field is-grouped">
      <div class="control">
        <label class="checkbox">
          <input id="remember_me" name="remember_me" type="checkbox" value="y">
          <span class="is-size-7">Remember me</span>
        </label>
      </div>
      <div class="control is-expanded has-text-right">
        <input 
          type="submit"
          @click.prevent="doValidate"
          name="submit_btn" 
          class="button is-link">
      </div>
    </div>
  </form>

  <div class="content is-size-7 has-text-centered">
    <p><a href="{{ url_for('admin_auth.forgot_password') }}">Forgot Password</a></p>
    <p><a href="{{ main_url }}">&larr; Go to main site</a></p>
  </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  new Vue({
    el: '#this-block',
    delimiters: ['[[', ']]'],
    data() {
      return {
        email: '',
        password: '',
        errorMsg: ['','']
      }
    },
    methods: {
      clearErrors() {
        for (let i=0; i<this.errorMsg.length;i++) {
          this.errorMsg[i] = ''
        }
      },
      hasError() {
        err = false
        for(let i=0; i<this.errorMsg.length; i++) {
          if(this.errorMsg[i] != '') err = true
        }
        return err
      },
      doValidate() {
        this.clearErrors()
        if (this.email.length == 0) {
          Vue.set(this.errorMsg, 0, 'This is a mandatory field')
        }
        if (this.password.length == 0) {
          Vue.set(this.errorMsg, 1, 'This is a mandatory field')
        }
        if (!this.hasError()) {
          this.$refs.loginForm.submit()
        }
      }
    }
  })
</script>
{% endblock %}

app/templates/admin_auth/reset_password.html
{% extends "admin_auth/base_auth.html" %}
{% block title %}Reset Password{% endblock %}

{% block app_content %}
<div id="this-block">

  <form
    ref="resetPasswordForm"
    action=""
    method="post"
    class="box">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

    <div class="notification is-info is-light is-flex-wrap-wrap is-size-7">
      Enter your new password
    </div>
    <div class="field">
      <div class="label">New Password</div>
      <div class="control has-icons-left">
        <input 
          name="password"
          class="input"
          type="password"
          v-model="password">
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </div>
      <p v-if="errorMsg[0]" class="help is-danger">[[ errorMsg[0] ]]</p>
    </div>

    <div class="field">
      <div class="label">Repeat Password</div>
      <div class="control has-icons-left">
        <input 
          name="password2"
          class="input"
          type="password"
          v-model="password2">
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </div>
      <p v-if="errorMsg[1]" class="help is-danger">[[ errorMsg[1] ]]</p>
    </div>

    <div class="field pt-3">
      <div class="control is-expanded has-text-right">
        <input 
          type="submit"
          @click.prevent="doValidate"
          name="submit_btn" 
          class="button is-link">
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script>
  new Vue({
    el: '#this-block',
    delimiters: ['[[', ']]'],
    data() {
      return {
        password: '',
        password2: '',
        errorMsg: ['','']
      }
    },
    methods: {
      clearErrors() {
        for (let i=0; i<this.errorMsg.length;i++) {
          this.errorMsg[i] = ''
        }
      },
      hasError() {
        err = false
        for(let i=0; i<this.errorMsg.length; i++) {
          if(this.errorMsg[i] != '') err = true
        }
        return err
      },
      doValidate() {
        this.clearErrors()
        if (this.password.length == 0) {
          Vue.set(this.errorMsg, 0, 'This is a mandatory field')
        } else if (this.password.length < 6) {
          Vue.set(this.errorMsg, 0, 'Minimum 6 characters')
        }
        if (this.password != this.password2) {
          Vue.set(this.errorMsg, 1, 'Passwords do not match')
        }
        if (!this.hasError()) {
          this.$refs.resetPasswordForm.submit()
        }
      }
    }
  })
</script>
{% endblock %}